<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleUserPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleUserPermissionRepository extends EntityRepository
{
}
