<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository 
{

	public function loadUserByUsername($username,$password)
    {	//echo "===".$username."=====".$password;exit;
        $data = $this->createQueryBuilder('u')
            ->where('u.username = :username And u.password = :password')
            ->setParameter('username', $username)
            ->setParameter('password', $password)
            ->getQuery()
            ->getOneOrNullResult();
            print_r($data);exit("===");
  
		return $data;
    }

  public function selectuser($em){
      $q = $em->createQuery('SELECT r FROM AdminBundle:User r WHERE r.deleted =:deleted')->setParameter('deleted', '0');
      $data = $q->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
     //  print_r($role);exit;
    return $data;

  }
  public function deleteuser($em,$id){
      $q = $em->createQuery('DELETE  FROM AdminBundle:User r
         WHERE u.id = :id'
        )->setParameter('id', $id);
     // $data = $q->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
      // print_r($role);exit;
    return true;

  }
}
